export const CREATE_USER_WITH_EMAIL_AND_PASSWORD_MUTATION_KEY = [
    "FIREBASE",
    "AUTH",
    "CREATE_USER_WITH_EMAIL_AND_PASSWORD_MUTATION"
] as const;
export const GET_REDIRECT_RESULT_MUTATION_KEY = ["FIREBASE", "AUTH", "GET_REDIRECT_RESULT_MUTATION"] as const;
export const SEND_EMAIL_VERIFICATION_MUTATION_KEY = ["FIREBASE", "AUTH", "SEND_EMAIL_VERIFICATION_MUTATION"] as const;
export const SIGN_IN_ANONYMOUSLY_MUTATION_KEY = ["FIREBASE", "AUTH", "SIGN_IN_ANONYMOUSLY_MUTATION"] as const;
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_MUTATION_KEY = [
    "FIREBASE",
    "AUTH",
    "SIGN_IN_WITH_EMAIL_AND_PASSWORD_MUTATION"
] as const;
export const SIGN_IN_WITH_REDIRECT_MUTATION_KEY = ["FIREBASE", "AUTH", "SIGN_IN_WITH_REDIRECT_MUTATION"] as const;
export const SIGN_IN_WITH_CREDENTIAL_MUTATION_KEY = ["FIREBASE", "AUTH", "SIGN_IN_WITH_CREDENTIAL_MUTATION"] as const;
export const LINK_WITH_CREDENTIAL_MUTATION_KEY = ["FIREBASE", "AUTH", "LINK_WITH_CREDENTIAL_MUTATION"] as const;
export const SIGN_OUT_MUTATION_KEY = ["FIREBASE", "AUTH", "SIGN_OUT"] as const;
export const REAUTHENTICATE_WITH_REDIRECT_MUTATION_KEY = ["FIREBASE", "AUTH", "REAUTHENTICATE_WITH_REDIRECT"] as const;
export const REAUTHENTICATE_WITH_CREDENTIAL_MUTATION_KEY = [
    "FIREBASE",
    "AUTH",
    "REAUTHENTICATE_WITH_CREDENTIAL"
] as const;
